# Generated by Django 3.2.7 on 2021-10-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
